export const LOGIN_SUCCESS = 'login_sucess'
export const LOGIN_FAIL = 'login_fail'
export const LOADING = 'loading'
export const SIGNUP_SUCCESS = 'signup_success'
export const SIGNUP = 'signup'
export const SIGNUP_FAIL = 'signup_fail'
export const GET_ERRORS = 'get_errors'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'